services:
  - type: web
    name: hdb-resale-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DB_PATH
        value: /opt/render/project/src/hdb_tracker.db
